### ISSUE TITLE
Could not set gcode style scheme

### ISSUE THREAD

**Issue by TurBoss** [KurtJacobson/hazzy#20]
I get this error when using GCode.xml style

```
HAZZY INFO: gcode style scheme found!
HAZZY INFO: hngc.lang found!
HAZZY ERROR: Could not set gcode style scheme!
Verify that the style scheme file and name are correct

(hazzy.py:13657): GtkSourceView-CRITICAL **: gtk_source_language_manager_set_search_path: assertion 'lm->priv->ids == NULL' failed
No Bookmarks
HAZZY ERROR - Traceback (most recent call last):
  File "/home/turboss/Sources/hazzy/hazzy/hazzy.py", line 1875, in <module>
    ui = Hazzy()
  File "/home/turboss/Sources/hazzy/hazzy/hazzy.py", line 499, in __init__
    self._init_gcode_preview()
  File "/home/turboss/Sources/hazzy/hazzy/hazzy.py", line 1111, in _init_gcode_preview
    self.preview_buf.set_style_scheme(self.sm.get_scheme(self.style_scheme))
TypeError: GtkSourceView.Buffer.set_style_scheme() argument 1 must be gtksourceview2.StyleScheme, not None
```

Thanks

**Comment by TurBoss** [comment]
It was my fault will fix :D

**Comment by KurtJacobson** [comment]
This is great! What did you do to cause the error? I will try and foolproof it ;)

**Comment by TurBoss** [comment]
this got fixed
thanks
